In [38]:
#SIMPLE NEURAL NETWORKS

In [29]:
import numpy as np

In [30]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [31]:
bias = [[2,4,6],[5,7,8],[3]]

inp = [2,4,3]

weight = [[1,0,0.2],[0,1,1],[0.5,0,1]]

In [32]:
level1 = np.dot(inp,weight[0]) + bias[0]
level1

array([4.6, 6.6, 8.6])

In [33]:
L1 = list(map(sigmoid,level1))
print(L1)

[0.9900481981330957, 0.9986414800495711, 0.9998159280950366]


In [34]:
level2 = np.dot(L1,weight[1]) + bias[1]
level2

array([6.99845741, 8.99845741, 9.99845741])

In [35]:
L2 = list(map(sigmoid,level2))
print(L2)

[0.9990875436242631, 0.9998764149531985, 0.9999545320500598]


In [36]:
level3 = np.dot(L2,weight[2]) + bias[2]
level3

array([4.4994983])

In [37]:
L3 = sigmoid(level3)
print("OUTPUT:",L3)

OUTPUT: [0.9890076]


In [42]:
#BASIC KERAS MODEL
from numpy import loadtxt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import pandas as pd

In [45]:
df = pd.read_csv('pima-indians-diabetes.data.csv')
df

6  148  72  35    0  33.6  0.627  50  1
0     1   85  66  29    0  26.6  0.351  31  0
1     8  183  64   0    0  23.3  0.672  32  1
2     1   89  66  23   94  28.1  0.167  21  0
3     0  137  40  35  168  43.1  2.288  33  1
4     5  116  74   0    0  25.6  0.201  30  0
..   ..  ...  ..  ..  ...   ...    ...  .. ..
762  10  101  76  48  180  32.9  0.171  63  0
763   2  122  70  27    0  36.8  0.340  27  0
764   5  121  72  23  112  26.2  0.245  30  0
765   1  126  60   0    0  30.1  0.349  47  1
766   1   93  70  31    0  30.4  0.315  23  0

[767 rows x 9 columns]

In [48]:
# load the dataset
dataset = loadtxt('pima-indians-diabetes.data.csv', delimiter=',')
# split into input (X) and output (y) variables
X = dataset[:,0:8]
y = dataset[:,8]


In [49]:
# define the keras model
model = Sequential()
model.add(Dense(12, input_shape=(8,), activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

Metal device set to: Apple M1


2023-05-02 15:26:24.166622: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-05-02 15:26:24.167235: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [50]:
# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [51]:
# fit the keras model on the dataset
model.fit(X, y, epochs=150, batch_size=10)

Epoch 1/150


2023-05-02 15:27:22.263513: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2023-05-02 15:27:22.501517: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


77/77 [==============================] - 3s 10ms/step - loss: 7.2297 - accuracy: 0.6068
Epoch 2/150
77/77 [==============================] - 0s 6ms/step - loss: 1.5697 - accuracy: 0.5951
Epoch 3/150
77/77 [==============================] - 0s 6ms/step - loss: 0.9894 - accuracy: 0.6146
Epoch 4/150
77/77 [==============================] - 0s 6ms/step - loss: 0.8064 - accuracy: 0.6276
Epoch 5/150
77/77 [==============================] - 0s 6ms/step - loss: 0.7374 - accuracy: 0.6341
Epoch 6/150
77/77 [==============================] - 0s 6ms/step - loss: 0.6941 - accuracy: 0.6615
Epoch 7/150
77/77 [==============================] - 0s 6ms/step - loss: 0.6616 - accuracy: 0.6680
Epoch 8/150
77/77 [==============================] - 0s 6ms/step - loss: 0.6410 - accuracy: 0.6836
Epoch 9/150
77/77 [==============================] - 0s 6ms/step - loss: 0.6324 - accuracy: 0.6758
Epoch 10/150
77/77 [==============================] - 0s 6ms/step - loss: 0.6189 - accuracy: 0.6602
Epoch 11/150
77/77 [

In [53]:
# evaluate the keras model
_, accuracy = model.evaluate(X, y)
print('Accuracy: %.2f' % (accuracy*100))

24/24 [==============================] - 0s 5ms/step - loss: 0.4884 - accuracy: 0.7656
Accuracy: 76.56
